<div>
    <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
        <div>
            <h1 class="h4 mb-1">Backups</h1>
            <p class="text-secondary small mb-0">Download the latest backup files generated by the system.</p>
        </div>
        <button type="button" class="btn btn-secondary d-inline-flex align-items-center gap-2"
            wire:click="refreshList" wire:loading.attr="disabled">
            <i class="bi bi-arrow-clockwise" aria-hidden="true" wire:loading.remove></i>
            <span wire:loading.remove>Refresh</span>
            <span class="spinner-border spinner-border-sm" aria-hidden="true" wire:loading></span>
        </button>
    </div>

    @if($errorMessage)
    <div class="alert alert-danger d-flex align-items-center gap-2" role="alert">
        <i class="bi bi-exclamation-triangle-fill"></i>
        <span>{{ $errorMessage }}</span>
    </div>
    @endif

    <div class="card shadow-sm">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
                <h2 class="h6 fw-semibold mb-0">Recent backups</h2>
{{--                <small class="text-secondary">Showing the last 5 files in the backups directory.</small>--}}
            </div>

            @if(empty($recentBackups))
            <p class="text-secondary mb-0">No backups found yet.</p>
            @else
            <div class="table-responsive">
                <table class="table table-sm align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th scope="col">File</th>
                            <th scope="col" style="width: 120px;">Size</th>
                            <th scope="col" style="width: 180px;">Last modified</th>
                            <th scope="col" class="text-end" style="width: 140px;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($recentBackups as $file)
                        <tr>
                            <td class="fw-semibold">{{ $file['name'] }}</td>
                            <td class="text-secondary">{{ $file['size'] }}</td>
                            <td class="text-secondary">{{ $file['modified'] }}</td>
                            <td class="text-end">
                                <a class="btn btn-sm btn-primary"
                                    href="{{ route('admin.backups.download', ['file' => $file['name']]) }}">
                                    <i class="bi bi-download me-1" aria-hidden="true"></i>Download
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif
        </div>
    </div>
</div>
