<div>
    <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
        <div>
            <h1 class="h4 mb-1">Backups</h1>
            <p class="text-secondary small mb-0">Download the latest backup files generated by the system.</p>
        </div>
        {{-- <button type="button" class="btn btn-secondary d-inline-flex align-items-center gap-2"
            wire:click="refreshList" wire:loading.attr="disabled">
            <i class="bi bi-arrow-clockwise" aria-hidden="true" wire:loading.remove></i>
            <span wire:loading.remove>Refresh</span>
            <span class="spinner-border spinner-border-sm" aria-hidden="true" wire:loading></span>
        </button> --}}
    </div>

    @if($errorMessage)
    <div class="alert alert-danger d-flex align-items-center gap-2" role="alert">
        <i class="bi bi-exclamation-triangle-fill"></i>
        <span>{{ $errorMessage }}</span>
    </div>
    @endif

    <div class="card shadow-sm">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
                <h2 class="h6 fw-semibold mb-0">Recent backups</h2>
{{--                <small class="text-secondary">Showing the last 5 files in the backups directory.</small>--}}
            </div>

            @if(empty($recentBackups))
            <p class="text-secondary mb-0">No backups found yet.</p>
            @else
            <div class="table-responsive">
                <table class="table table-sm align-middle mb-0">
                    <thead class="table-light">
                        <tr>
                            <th scope="col">File</th>
                            <th scope="col" style="width: 120px;">Size</th>
                            <th scope="col" style="width: 180px;">Last modified</th>
                            <th scope="col" class="text-end" style="width: 140px;">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($recentBackups as $file)
                        <tr>
                            <td class="fw-semibold">{{ $file['name'] }}</td>
                            <td class="text-secondary">{{ $file['size'] }}</td>
                            <td class="text-secondary">{{ $file['modified'] }}</td>
                            <td class="text-end">
                                <a class="btn btn-sm btn-secondary"
                                    href="{{ route('admin.backups.download', ['file' => $file['name']]) }}">
                                    <i class="bi bi-download me-1" aria-hidden="true"></i>Download
                                </a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            @endif
        </div>
    </div>

    <div class="card shadow-sm mt-4">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
                <div>
                    <h3 class="h6 fw-semibold mb-1">Restore database</h3>
                    <p class="small text-secondary mb-0">Upload a .gz export to restore the database.</p>
                </div>
            </div>

            <form wire:submit="restoreBackup" class="row gy-3 align-items-end">
                <div class="col-12 col-md">
                    <label class="form-label small mb-1">Select backup file (.gz)</label>
                    <input 
                        type="file" 
                        wire:model.live="restoreFile" 
                        accept=".gz"
                        {{ $isRestoring ? 'disabled' : '' }}
                        class="form-control {{ str_starts_with($restoreMessage, 'Error') ? 'is-invalid' : '' }}"
                    >
                    @error('restoreFile') 
                        <div class="text-danger small mt-1">{{ $message }}</div> 
                    @enderror
                    <div class="d-none align-items-center gap-2 text-secondary small"
                         wire:loading.class.remove="d-none"
                         wire:target="restoreFile">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                        <span>Uploading file...</span>
                    </div>
                    @if($restoreMessage)
                        @if(str_starts_with($restoreMessage, 'Error'))
                            <div class="invalid-feedback d-block">{{ $restoreMessage }}</div>
                        @else
                            <div class="form-text text-secondary">{{ $restoreMessage }}</div>
                        @endif
                    @endif
                </div>

                <div class="col-auto">
                    <button 
                        type="submit" 
                        {{ $isRestoring ? 'disabled' : '' }}
                        class="btn btn-secondary d-inline-flex align-items-center gap-2"
                        wire:loading.attr="disabled"
                        wire:target="restoreBackup,restoreFile"
                    >
                        <span wire:loading wire:target="restoreBackup" class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                        <span>{{ $isRestoring ? 'Restoring...' : 'Restore database' }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="card shadow-sm mt-3">
        <div class="card-body">
            <div class="d-flex align-items-center justify-content-between mb-3 flex-wrap gap-2">
                <div>
                    <h3 class="h6 fw-semibold mb-1">Restore documents</h3>
                    <p class="small text-secondary mb-0">Upload a .zip archive to restore uploaded documents.</p>
                </div>
            </div>

            <form wire:submit="restoreDocuments" class="row gy-3 align-items-end">
                <div class="col-12 col-md">
                    <label class="form-label small mb-1">Select ZIP file</label>
                    <input 
                        type="file" 
                        wire:model.live="restoreDocumentsFile" 
                        accept=".zip"
                        {{ $isRestoringDocuments ? 'disabled' : '' }}
                        class="form-control {{ str_starts_with($restoreDocumentsMessage, 'Error') ? 'is-invalid' : '' }}"
                    >
                    @error('restoreDocumentsFile') 
                        <div class="text-danger small mt-1">{{ $message }}</div> 
                    @enderror
                    <div class="d-none align-items-center gap-2 text-secondary small"
                         wire:loading.class.remove="d-none"
                         wire:target="restoreDocumentsFile">
                        <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                        <span>Uploading file...</span>
                    </div>
                    @if($restoreDocumentsMessage)
                        @if(str_starts_with($restoreDocumentsMessage, 'Error'))
                            <div class="invalid-feedback d-block">{{ $restoreDocumentsMessage }}</div>
                        @else
                            <div class="form-text text-secondary">{{ $restoreDocumentsMessage }}</div>
                        @endif
                    @endif
                </div>

                <div class="col-auto">
                    <button 
                        type="submit" 
                        {{ $isRestoringDocuments ? 'disabled' : '' }}
                        class="btn btn-secondary d-inline-flex align-items-center gap-2"
                        wire:loading.attr="disabled"
                        wire:target="restoreDocuments,restoreDocumentsFile"
                    >
                        <span wire:loading wire:target="restoreDocuments" class="spinner-border spinner-border-sm" aria-hidden="true"></span>
                        <span>{{ $isRestoringDocuments ? 'Restoring...' : 'Restore documents' }}</span>
                    </button>
                </div>
            </form>
        </div>
    </div>

</div>
